spring.datasource.url=jdbc:postgresql://HOST:PORT/datastore_sow7
spring.datasource.username=datastore_sow7_user
spring.datasource.password=aZUGfvTqelpMlUxWJCaxVDvRXdAJ6kVU


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=mysupersecretkeythatismorethan32characterslong123
jwt.expiration=86400000
logging.level.org.springframework.security=DEBUG
server.port=8081
