spring.application.name=datastore
spring.datasource.url=jdbc:postgresql://localhost:5432/datastore
spring.datasource.username=postgres
spring.datasource.password=0000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=mysupersecretkeythatismorethan32characterslong123
jwt.expiration=86400000
logging.level.org.springframework.security=DEBUG
server.port=8081
